public with sharing class VerifyDuplicates {
    public static void VerifyDuplicatesInFreightInsert(List<Freight__c> newRecordList){

    }
    public static void VerifyDuplicatesInFreightUpdate(List<Freight__c> newRecordList){

    }
    public static void VerifyDuplicatesInMarginInsert(List<Freight__c> newRecordList){
        
    }
    public static void VerifyDuplicatesInMarginUpdate(List<Freight__c> newRecordList){

    }
}